server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lou..200499
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      # ?????????filters????????sql?????'wall'?????
#      filter:
#        stat:
#          merge-sql: true
#          slow-sql-millis: 5000
#      #3.??????
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        #???????URL
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable: true
#        session-stat-max-count: 100
#      stat-view-servlet:
#        enabled: true
#        # ????????
#        url-pattern: /druid/*
#        reset-enable: true
#        #?????????????
#        login-username: admin
#        login-password: admin
#        allow: 127.0.0.1
#        #deny: 192.168.1.100