// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.leo.cloudhubserver.model.wrapper;

public final class ResponseWrapperProto {
  private ResponseWrapperProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    java.lang.String getError();
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    int getLoadingCount();
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    boolean containsLoading(
        java.lang.String key);
    /**
     * Use {@link #getLoadingMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getLoading();
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getLoadingMap();
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */

    /* nullable */
java.lang.String getLoadingOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */

    java.lang.String getLoadingOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code ResponseWrapper}
   */
  public static final class ResponseWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseWrapper)
      ResponseWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseWrapper.newBuilder() to construct.
    private ResponseWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public ResponseWrapper() {
      error_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetLoading();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.class, com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    @java.lang.Override
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOADING_FIELD_NUMBER = 3;
    private static final class LoadingDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_LoadingEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> loading_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLoading() {
      if (loading_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LoadingDefaultEntryHolder.defaultEntry);
      }
      return loading_;
    }

    public int getLoadingCount() {
      return internalGetLoading().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */

    @java.lang.Override
    public boolean containsLoading(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetLoading().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLoadingMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLoading() {
      return getLoadingMap();
    }
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getLoadingMap() {
      return internalGetLoading().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getLoadingOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLoading().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; loading = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getLoadingOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLoading().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetLoading(),
          LoadingDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetLoading().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        loading__ = LoadingDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, loading__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper)) {
        return super.equals(obj);
      }
      com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper other = (com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getError()
          .equals(other.getError())) return false;
      if (!internalGetLoading().equals(
          other.internalGetLoading())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      if (!internalGetLoading().getMap().isEmpty()) {
        hash = (37 * hash) + LOADING_FIELD_NUMBER;
        hash = (53 * hash) + internalGetLoading().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseWrapper)
        com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetLoading();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableLoading();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.class, com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.Builder.class);
      }

      // Construct using com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        error_ = "";

        internalGetMutableLoading().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.internal_static_ResponseWrapper_descriptor;
      }

      @java.lang.Override
      public com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper getDefaultInstanceForType() {
        return com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper build() {
        com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper buildPartial() {
        com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper result = new com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper(this);
        int from_bitField0_ = bitField0_;
        result.code_ = code_;
        result.error_ = error_;
        result.loading_ = internalGetLoading();
        result.loading_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper) {
          return mergeFrom((com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper other) {
        if (other == com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        internalGetMutableLoading().mergeFrom(
            other.internalGetLoading());
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                code_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                error_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                loading__ = input.readMessage(
                    LoadingDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableLoading().getMutableMap().put(
                    loading__.getKey(), loading__.getValue());
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 2;</code>
       * @return The error.
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       * @return The bytes for error.
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @param value The bytes for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> loading_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetLoading() {
        if (loading_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              LoadingDefaultEntryHolder.defaultEntry);
        }
        return loading_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableLoading() {
        onChanged();;
        if (loading_ == null) {
          loading_ = com.google.protobuf.MapField.newMapField(
              LoadingDefaultEntryHolder.defaultEntry);
        }
        if (!loading_.isMutable()) {
          loading_ = loading_.copy();
        }
        return loading_;
      }

      public int getLoadingCount() {
        return internalGetLoading().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */

      @java.lang.Override
      public boolean containsLoading(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetLoading().getMap().containsKey(key);
      }
      /**
       * Use {@link #getLoadingMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getLoading() {
        return getLoadingMap();
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getLoadingMap() {
        return internalGetLoading().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getLoadingOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLoading().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getLoadingOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetLoading().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearLoading() {
        internalGetMutableLoading().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */

      public Builder removeLoading(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableLoading().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableLoading() {
        return internalGetMutableLoading().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */
      public Builder putLoading(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableLoading().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; loading = 3;</code>
       */

      public Builder putAllLoading(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableLoading().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseWrapper)
    }

    // @@protoc_insertion_point(class_scope:ResponseWrapper)
    private static final com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper();
    }

    public static com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ResponseWrapper>() {
      @java.lang.Override
      public ResponseWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResponseWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leo.cloudhubserver.model.wrapper.ResponseWrapperProto.ResponseWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseWrapper_LoadingEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseWrapper_LoadingEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\"\216\001\n\017ResponseWrapper\022\014\n\004" +
      "code\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\022.\n\007loading\030\003 \003" +
      "(\0132\035.ResponseWrapper.LoadingEntry\032.\n\014Loa" +
      "dingEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001B<\n$com.leo.cloudhubserver.model.wrappe" +
      "rB\024ResponseWrapperProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResponseWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResponseWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseWrapper_descriptor,
        new java.lang.String[] { "Code", "Error", "Loading", });
    internal_static_ResponseWrapper_LoadingEntry_descriptor =
      internal_static_ResponseWrapper_descriptor.getNestedTypes().get(0);
    internal_static_ResponseWrapper_LoadingEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseWrapper_LoadingEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
